/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export type ImageProcessingOption = 'asis' | 'cartoon' | 'nobg';

export interface Vehicle {
  id: string;
  name: string;
  type: string; // e.g., 'Danfo (16-Seater Bus)', 'Korope (6-Seater Bus)', 'Keke Marwa (3-Wheeler Tricycle)', 'Okada (Commercial Bike)', 'Heavy Semi-Truck', 'Delivery Box Van', 'Custom'
  purchasePrice: number;
  annualDepreciationRate: number; // percentage, e.g., 12%
  expectedMaintenanceMonthly: number;
  fuelPriceRate: number; // fuel cost per mile/km
  insurancePremiumMonthly: number;
  annualDistanceMiles: number; // expected driven distance per year
  monthlyRevenue: number; // revenue generated by this vehicle
  inflationRate: number; // percentage, e.g., 2.5%
  dividendPayoutRate: number; // percentage of net profit distributed as dividends, e.g., 40%
  imageOption: ImageProcessingOption;
  originalImage: string | null; // Base64 or URL
  processedImage: string | null; // Base64 or URL
  createdAt: string;
  
  // Custom enhanced Nigerien transport inputs
  salvageValuePercent: number; // Salvage percentage, e.g., 15
  driverMonthlySalary: number; // Monthly driver salary/allowance
  leviesAndTaxesMonthly: number; // Daily ticket fees / Union dues / levies scaled monthly

  // Custom investor and rental tenor parameters
  investorSharePercent: number; // Percentage of purchase price funded by investors (0-100%)
  rentalTenorYears: number; // Rent tenancy duration (1-10 years)
  fixedDailyRent: number; // Fixed daily rent amount (₦/day) paid by renter
  passOpexToRenter: boolean; // Toggle to move daily operational expenses to renter (fuel, driver wage, union dues)
  fuelConsumptionDaily: number; // Fuel used per day in liters
  fuelPricePerLiter: number; // Base fuel price per liter
  activeDaysPerYear: number; // Number of operational days per year (e.g. 312 days)
  runAsCompany?: boolean; // Toggle to choose company operations (driver hired) instead of rental lease model
}

export interface DetailedFinancialYear {
  year: number;
  revenue: number;
  maintenanceCost: number;
  fuelCost: number;
  insuranceCost: number;
  driverWagesCost: number;
  leviesCost: number;
  totalCostOfOwnership: number;
  depreciatedValue: number;
  netProfit: number;
  dividendPayout: number;
  roi: number; // Asset Return on Investment
  irr: number; // Asset Internal Rate of Return (IRR)
  moic: number; // Asset Multiple on Invested Capital
  cumulativeRevenue: number;
  cumulativeExpenses: number;
  cumulativeDividends: number;

  // Leverage & Equity split details
  ownerCapitalInvested: number;
  investorCapitalInvested: number;
  ownerShareDividends: number;
  investorShareDividends: number;
  ownerRoi: number; // Owner portion ROI
  ownerIrr: number; // Owner portion IRR
  ownerMoic: number; // Owner portion MOIC
}

export interface PortfolioSummary {
  totalPurchaseValue: number;
  annualRevenue: number;
  annualOperatingCost: number;
  averageRoi: number;
  averageIrr: number;
  averageMoic: number;
  projected10YrDividends: number;

  // Aggregate Equity-specific summaries
  totalOwnerEquity: number;
  totalInvestorEquity: number;
  averageOwnerRoi: number;
  averageOwnerIrr: number;
  averageOwnerMoic: number;
}
